
networks:
  users-net:
    driver: bridge

services:
  users-query:
    image: users-query
    container_name: users-query
    networks:
      - users-net
    ports:
      - 8081:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  users-command:
    image: users-command
    container_name: users-command
    networks:
      - users-net
    ports:
      - 8082:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  users-api-gateway:
    image: users-api-gateway
    container_name: users-api-gateway
    networks:
      - users-net
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
